### ISSUE TITLE
vdr 2.3.1 start fails

### ISSUE THREAD

**Issue by dersch81** [flensrocker/vdr-plugin-dynamite#6]
Hi, 

i've been using vdr from this source up to now but not with 2.3.1 i'm facing problems:

`May  6 23:00:45 superserver vdr: [12894] VDR version 2.3.1 started
May  6 23:00:45 superserver vdr: [12894] codeset is 'UTF-8' - known
May  6 23:00:45 superserver vdr: [12894] use of environment variable VDR_CHARSET_OVERRIDE (ISO-8859-15) is deprecated!
May  6 23:00:45 superserver vdr: [12894] override character table is 'ISO-8859-15'
May  6 23:00:45 superserver vdr: [12894] loading plugin: /usr/local/lib/vdr/libvdr-vnsiserver.so.2.3.1
May  6 23:00:45 superserver vdr: [12894] loading plugin: /usr/local/lib/vdr/libvdr-xvdr.so.2.3.1
May  6 23:00:45 superserver vdr: [12894] ERROR: /usr/local/lib/vdr/libvdr-xvdr.so.2.3.1: undefined symbol: Timers
May  6 23:00:45 superserver vdr: [12894] deleting plugin: vnsiserver
May  6 23:00:45 superserver vdr: [12894] exiting, exit code 2
`
What is the problem with the xvdr.so.2.3.1?

**Comment by flensrocker** [comment]
I don't know. Is it ported to vdr 2.3.1 yet? There are some significant changes in accessing timers, channels and recordings from plugins.

Make sure you have a clean copy of xvdr and build them against the right vdr-headers.

Otherwise ask the author of xvdr, this is the repository of dynamite... :)

**Comment by dersch81** [comment]
Honestly speaking i don't use xvdr anymore. But also if i complie vdr without that plugin i get the same error.
